name: Upload dist/ folder to cPanel Web Disk

on:
  push:
    branches:
      - main  # Trigger only on main branch changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main branch
        uses: actions/checkout@v3

      - name: Install WebDAV client (cadaver)
        run: sudo apt-get install cadaver -y

      - name: Upload dist/ folder to cPanel Web Disk
        env:
          WEBDISK_USERNAME: ${{ secrets.WEBDISK_USERNAME }}
          WEBDISK_PASSWORD: ${{ secrets.WEBDISK_PASSWORD }}
          WEBDISK_URL: ${{ secrets.WEBDISK_SERVER }}
        run: |
          echo "lcd dist" > upload.txt
          echo "cd public_html" >> upload.txt
          echo "mput *" >> upload.txt
          echo "quit" >> upload.txt

          echo -e "${WEBDISK_PASSWORD}\n" | cadaver "${WEBDISK_URL}" < upload.txt
